Repository jisu-0305/SsafyTrip, pull requests merged in 2025-01, with the labels that each got.

#96 [CI] BE workflow 수정
  .github/workflows/deploy-backend.yml
Labels: BE

#101 [FE] hotfix: 회원가입 오류 수정
  src/views/auth/AuthRegisterView.vue
Labels: FE

#99 [BE]fix: "comment생성 처리방식 변경"
  src/main/java/com/trip/attraction/service/AttractionService.java
  src/main/java/com/trip/attraction/service/AttractionServiceImpl.java
  src/main/java/com/trip/comment/controller/CommentController.java
  src/main/resources/application.properties
Labels: BE

#103 [FE] hotfix: 여행 스케줄 생성 데이터 값 변경
  src/api/axios.js
  src/stores/planStores.js
Labels: BE

#105 [BE] refact: AI 모델 전환 #75
  pom.xml
  src/main/java/com/trip/ai/controller/AIController.java
  src/main/java/com/trip/ai/service/AIServiceImpl.java
  src/main/java/com/trip/review/service/ReviewSerivce.java
  src/main/java/com/trip/review/util/S3Util.java
  src/main/java/com/trip/translation/dto/Translation.java
  src/main/java/com/trip/translation/dto/TranslationResponse.java
  src/main/java/com/trip/translation/service/TranslationService.java
  src/main/java/com/trip/translation/service/TranslationServiceImpl.java
  src/main/resources/application.properties
Labels: BE

#104 [BE] feature: "member 단위테스트"
  src/test/java/com/trip/member/MemberControllerTest.java
  src/test/java/com/trip/member/MemberIntegrationTest.java
  src/test/java/com/trip/member/MemberRepositoryTest.java
  src/test/java/com/trip/member/MemberServiceTest.java
Labels: BE

#110 [CI] hotfix: BE 자동배포 이후 검증 단계에서의 오류 해결 #109
  .github/workflows/deploy-backend.yml
Labels: CI/CD

#112 Feature/be/111
  src/main/java/com/trip/notice/controller/NoticeController.java
  src/main/java/com/trip/notice/dto/NoticeImageResponseDTO.java
  src/main/java/com/trip/notice/service/NoticeService.java
  src/main/java/com/trip/notice/service/NoticeServiceImpl.java
Labels: BE

#113 [refact] 아이콘 반영, 회원가입 이름 수정
  index.html
  src/views/auth/AuthRegisterView.vue
Labels: FE

#117 Feature/be/116
  src/main/java/com/trip/member/controller/MemberController.java
  src/main/java/com/trip/question/controller/QuestionController.java
Labels: BE

#119 chore: README 작성
  README.md
Labels: etc
